config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  post "/graphql", to: "graphql#execute"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'

  root to: redirect('tags')

  get :stats, to: 'stats#index'

  resources :tags do
    get :popular, on: :collection
    get :broad, on: :collection
    get :all, on: :collection
  end

  resources :instances, constraints: { id: /.*/ } do
    get :popular, on: :collection
    get :alphabetical, on: :collection
  end

  resources :languages, only: [:index, :show] do
    get :popular, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gutentag/tagging.rb
class Gutentag::Tagging < ActiveRecord::Base
  self.table_name = "gutentag_taggings"

  belongs_to :taggable, :polymorphic => true
  belongs_to :tag, :class_name => "Gutentag::Tag", :counter_cache => true

  validates :taggable, :presence => true
  validates :tag,      :presence => true
  validates :tag_id,   :uniqueness => {
    :scope => %i[ taggable_id taggable_type ]
  }
end

app/models/instance.rb
class Instance < ApplicationRecord
  include PgSearch

  has_many :toots
  has_many :tags, through: :toots

  pg_search_scope :search, against: :host, using: { tsearch: { prefix: true } }
end

app/models/toot.rb
require 'elasticsearch/model'

class Toot < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  Gutentag::ActiveRecord.call self

  belongs_to :instance

  after_save    { IndexerWorker.perform_async(:index,  id) }
  after_destroy { IndexerWorker.perform_async(:delete, id) }

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :tag_names, type: :keyword
      indexes :language, type: :keyword
      indexes :created_at, type: :date
      indexes :instance do
        indexes :host, type: :keyword
      end
    end
  end

  def as_indexed_json(_options={})
    self.as_json(
      only: [:id, :language, :created_at, :guid, :sensitive, :tag_names],
      include: {
        instance: { only: :host },
      })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      throttle_data: request.env['rack.attack.throttle_data']
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = MastodonTagsExplorerSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  def index
    @page_title = 'Trending instances'

    instances = InstancesQuery.new.trending
    @instances = instances.buckets
  end

  def popular
    @page_title = 'Popular instances'

    @instances = InstancesQuery.new.popular.page(params[:page]).per(26)

    render :index
  end

  def alphabetical
    @page_title = 'All instances'

    instances = InstancesQuery.new.alphabetical
    instances = InstancesQuery.new(instances).search(params[:q]) if params[:q].present?

    @instances = instances.page(params[:page]).per(26)

    render :index
  end

  def show
    @instance = Instance.find_by!(host: params[:id])

    @page_title = @instance.host
    @page_description = "#{@instance.host} statistics on Mastodon Tags Explorer"

    @tags = @instance.tags
                     .order(taggings_count: :desc)
                     .distinct
                     .page(params[:page])
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def index
    @page_title = 'Trending languages'
    @page_description = 'Languages trending on Mastodon Tags Explorer'

    @languages = LanguagesQuery.new.trending.buckets
  end

  def popular
    @page_title = 'Popular languages'
    @page_description = 'Languages popular on Mastodon Tags Explorer'

    @languages = LanguagesQuery.new.popular

    render :index
  end

  def show
    @toots = Toot.where(language: params[:id])
    @language = LanguageList::LanguageInfo.find(params[:id])

    @page_title = @language.name
    @page_description = "#{@language.name} language statsu on Mastodon Tags Explorer"

    @tags = Gutentag::Tag.joins('INNER JOIN gutentag_taggings ON gutentag_tags.id = gutentag_taggings.tag_id')
                         .joins('INNER JOIN toots ON gutentag_taggings.taggable_id = toots.id')
                         .where('toots.language = ?', params[:id])
                         .order(taggings_count: :desc)
                         .distinct
                         .page(params[:page])

    @instances = Instance.all
                         .joins(:toots)
                         .where('toots.language = ?', params[:id])
                         .distinct
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    @page_title = 'Global stats'
    @page_description = 'Global statistics for Mastodon Tags Explorer'

    @tags_count = Gutentag::Tag.all.count
    @toots_count = Toot.all.count
    @instances_count = Instance.all.count

    json_resp = {
      tags_count: @tags_count,
      toots_count: @toots_count,
      instances_count: @instances_count,
    }

    respond_to do |format|
      format.json { render json: json_resp }
      format.html { render :index }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @page_title = 'Trending tags'
    tags = TagsQuery.new.trending
    @tags = tags.buckets
  end

  def popular
    @page_title = 'Popular tags'
    @tags = TagsQuery.new.popular.page(params[:page])
    render :index
  end

  def broad
    @page_title = 'Broad tags'
    @tags = TagsQuery.new.broad.page(params[:page])
    render :index
  end

  def all
    @page_title = 'All tags'
    tags = TagsQuery.new.all
    tags = TagsQuery.new(tags).search(params[:q]) if params[:q].present?
    @tags = tags.page(params[:page])

    render :index
  end

  def show
    @tag = Gutentag::Tag.find_by!(name: params[:id])

    @page_title = "##{@tag.name}"
    @page_description = "##{@tag.name} hashtag statistics on Mastodon Tags Explorer"

    @instances_count = Instance.where(
      id: Toot.tagged_with(names: [@tag.name]).select(:instance_id)
    ).count

    @instances = Instance.all
                         .left_joins(:tags)
                         .group(:id)
                         .order('COUNT(gutentag_tags.id) DESC')
                         .where('gutentag_tags.name = ?', @tag.name)
                         .limit(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
  def language_info_from_code(code)
    LanguageList::LanguageInfo.find(code)
  end
end

app/views/instances/_instance.html.slim
- tag_context ||= nil

.box
  h5.title.is-5
    = link_to instance.host, instance_path(instance.host)

  - if tag_context.present?
    a.button.is-small(
      href="https://#{instance.host}/web/timelines/tag/#{tag_context.name}"
      target="_blank"
    ) See toots &rarr;

app/views/instances/index.html.slim
h1.title Known instances

.level
  .level-left
    .tabs
      ul
        = active_link_to 'Trending', instances_path, class_active: 'is-active', wrap_tag: :li, active: :exclusive
        = active_link_to 'Popular', popular_instances_path, class_active: 'is-active', wrap_tag: :li, active: :exclusive
        = active_link_to 'Alphabetical', alphabetical_instances_path, class_active: 'is-active', wrap_tag: :li

  .level-right
    .level-item
      = form_tag alphabetical_instances_path, method: :get do
        .field.has-addons
          p.control
            input.input(placeholder="Search a tag..." name="q" value=params[:q])
          p.control
            button.button Search

- @instances.each_slice(2) do |chunk|
  .columns
    - chunk.each do |instance|
      .column
        = render partial: 'instances/instance', locals: { instance: instance.respond_to?(:record) ? instance.record : instance }

= paginate @instances if defined? @instances.total_pages

app/views/instances/show.html.slim
.columns.is-marginless
  .column
    div
      h1.title.is-2
        | #{@instance.host}

  .column
    .level
      .level-item.has-text-centered
        div
          p.heading Tagged toots
          p.title = @instance.toots.count

      .level-item.has-text-centered
        div
          p.heading Tags
          p.title = @instance.tags.count

hr

- @tags.each do |tag|
  = render partial: 'tags/tag', locals: { tag: tag }

= paginate @tags

app/views/languages/_language.html.slim
- meta ||= []

a.box(href=language_path(info.iso_639_1))
  .columns
    .column.is-1
      = "##{index}"

    .column
      h3.title.is-4
        = language_info_from_code(info.name).try(:name)
      .subtitle
        = "#{info.iso_639_3} (#{info.iso_639_1})"

    .column.is-2
      .level
        - meta.each do |m|
          .level-item.has-text-right
            div
              p.heading = m[:label]
              p.title = m[:number]

app/views/languages/index.html.slim
.level
  .level-left
    .tabs
      ul
        = active_link_to 'Trending', languages_path, class_active: 'is-active', wrap_tag: :li, active: :exclusive
        = active_link_to 'Popular', popular_languages_path, class_active: 'is-active', wrap_tag: :li, active: :exclusive

- @languages.each_with_index do |language, index|
  - if language.respond_to?(:record)
    = render partial: 'languages/language', locals: { index: index + 1,
                                                      info: language.record,
                                                      meta: [{ label: 'Score', number: language.score.round(3) }] }
  - else
    = render partial: 'languages/language', locals: { index: index + 1,
                                                      info: language[:info],
                                                      meta: [{ label: 'Toots', number: language[:count] }] }

app/views/languages/show.html.slim
.columns.is-marginless
  .column
    h1.title.is-2
      = @language.name

  .column
    .level
      .level-item.has-text-centered
        div
          p.heading Toots
          p.title = @toots.count

      .level-item.has-text-centered
        div
          p.heading Tags
          p.title = @tags.total_count

      .level-item.has-text-centered
        div
          p.heading Instances
          p.title = @instances.count

hr

- if @tags.current_page == 1
  h2.is-4.title.has-text-centered Trends
  h3.subtitle.has-text-centered Toots creation over time
  = area_chart @toots.where('created_at >= ?', DateTime.now - 20.hours).group_by_hour(:created_at).count
  hr

h2.is-4.title.has-text-centered Most popular tags

- @tags.each do |tag|
  = render partial: 'tags/tag', locals: { tag: tag }

= paginate @tags

app/views/layouts/_ga.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV['GA_ID'] %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<%= ENV['GA_ID'] %>');
</script>

app/views/layouts/application.html.slim
doctype html
html
  head
    = display_meta_tags title: 'Mastodon Tags Explorer'

    meta(name="viewport" content="width=device-width, initial-scale=1")

    = csrf_meta_tags
    = csp_meta_tag

    = render 'layouts/ga'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/bulma/0.7.0/css/bulma.min.css', media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'

  body
    nav(class="navbar is-light" role="navigation" aria-label="main navigation" data-controller="navbar")
      div(class="container")
        div(class="navbar-brand")
          a(href="/" class="navbar-item")
            | Mastodon Tags Explorer
            .tag.is-danger.is-small(style="margin-left: 0.5rem;") Beta

          a(role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-action="click->navbar#toggleMenu")
            span aria-hidden="true"
            span aria-hidden="true"
            span aria-hidden="true"

        div(class="navbar-menu" data-target="navbar.menu")
          div(class="navbar-end")
            = active_link_to 'Tags', tags_path, class: 'navbar-item', class_active: 'is-active'
            = active_link_to 'Instances', instances_path, class: 'navbar-item', class_active: 'is-active'
            = active_link_to 'Languages', languages_path, class: 'navbar-item', class_active: 'is-active'
            = active_link_to 'Stats', stats_path, class: 'navbar-item', class_active: 'is-active'

    .container
      .columns
        .column.is-8.is-offset-2
          = yield

    footer.footer(style="margin-top: 2rem")
      .container
        .content.has-text-centered
          a.bmc-button(target="_blank" href="https://www.buymeacoffee.com/mxb")
            img(src="https://www.buymeacoffee.com/assets/img/BMC-btn-logo.svg" alt="Buy me a coffee")
            span(style="margin-left:5px") Buy me a coffee

          br

          | <strong>Mastodon Tags Explorer</strong> by <a href="https://hcxp.co/@mb">@mb</a> • <a href="https://mastodon.social/@tagsexplorer">@tagsexplorer</a> • <a href="https://github.com/mbajur/mastodon-tags-explorer">Source code</a>

app/views/stats/index.html.slim
h1.title.has-text-centered Global stats

hr

.level(data-controller="stats-counters")
  .level-item.has-text-centered
    div
      p.heading Tags
      p.title(data-target="stats-counters.tagsCount")
        = @tags_count

  .level-item.has-text-centered
    div
      p.heading Toots processed
      p.title(data-target="stats-counters.tootsCount")
        = @toots_count

  .level-item.has-text-centered
    div
      p.heading Instances
      p.title(data-target="stats-counters.instancesCount")
        = @instances_count

hr

.has-text-centered.mb-2
  p.subtitle Tags processed

= area_chart Gutentag::Tag.all.where('created_at >= ?', DateTime.now - 7.days).group_by_day(:created_at).count

hr

.has-text-centered.mb-2
  p.subtitle Toots processed

= area_chart Toot.all.where('created_at >= ?', DateTime.now - 7.days).group_by_day(:created_at).count

hr

.has-text-centered.mb-2
  p.subtitle New instances

= area_chart Instance.all.where('created_at >= ?', DateTime.now - 7.days).group_by_day(:created_at).count

app/views/tags/_tag.html.slim
a.box(href=tag_path(tag.name))
  .columns
    .column
      h3.title.is-4
        | ##{tag.name}

    .column
      .level.is-mobile
        .level-item.has-text-centered.is-6
          div
            p.heading Toots
            p.title = tag.taggings.count

        .level-item.has-text-centered.is-6
          div
            p.heading Instances
            p.title = tag.instances_count

app/views/tags/index.html.slim
h1.title Known tags

.level
  .level-left
    .tabs
      ul
        = active_link_to 'Trending', tags_path, class_active: 'is-active', wrap_tag: :li, active: :exclusive
        = active_link_to 'Popular', popular_tags_path, class_active: 'is-active', wrap_tag: :li
        = active_link_to 'Broad', broad_tags_path, class_active: 'is-active', wrap_tag: :li
        = active_link_to 'All', all_tags_path, class_active: 'is-active', wrap_tag: :li

  .level-right
    .level-item
      = form_tag all_tags_path, method: :get do
        .field.has-addons
          p.control
            input.input(placeholder="Search a tag..." name="q" value=params[:q])
          p.control
            button.button Search

/ = debug @tags
- @tags.each do |tag|
  = render partial: 'tags/tag', locals: { tag: tag.respond_to?(:record) ? tag.record : tag }

- if @tags.empty?
  .box.has-text-centered.py-2
    h2.title.is-4 No tags to show
    p There are currently no tags to show for given filters. Please check back later.

= paginate @tags if defined? @tags.total_pages

app/views/tags/show.html.slim
.columns.is-marginless
  .column
    h1.title.is-2
      | ##{@tag.name}

  .column
    .level
      .level-item.has-text-centered
        div
          p.heading Toots
          p.title = @tag.taggings_count

      .level-item.has-text-centered
        div
          p.heading Instances
          p.title = @instances_count

hr

.has-text-centered.mb-2
  h2.title.is-3 Top instances
  p.subtitle with highest usage of ##{@tag.name} hashtag

- @instances.each_slice(2) do |chunk|
  .columns
    - chunk.each do |instance|
      .column.is-6
        = render instance, tag_context: @tag

hr

.columns
  .column.is-6
    .has-text-centered.mb-2
      h2.title.is-4 Trends
      p.subtitle tag usage over time

    = column_chart @tag.taggings.where('created_at >= ?', DateTime.now - 7.days).group_by_day(:created_at).count, height: 10
    = area_chart @tag.taggings.where('created_at >= ?', DateTime.now - 20.hours).group_by_hour(:created_at).count, height: 10

  .column.is-6
    .has-text-centered.mb-2
      h2.title.is-4 Top languages
      p.subtitle used in toots tagged with ##{@tag.name}

    = pie_chart Toot.tagged_with(names: [@tag.name]).where.not(language: nil).group(:language).count, legend: 'bottom'